import React, { useEffect, useState } from 'react';
import { CheckCircle2, ClipboardList } from 'lucide-react';
import { completeTask, fetchTasks } from '../../services/api';

export const SuperAdminTasksPanel: React.FC<{ token: string }> = ({ token }) => {
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    try {
      const result = await fetchTasks(token);
      setTasks(result.data?.content || []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    window.addEventListener('mock-state-updated', load);
    return () => window.removeEventListener('mock-state-updated', load);
  }, [token]);

  return (
    <div className="space-y-5 max-w-7xl p-6">
      <div>
        <h2 className="text-lg font-semibold text-[#F5F5F5]">Tasks</h2>
        <p className="text-xs text-[#555] mt-0.5">Review workflow tasks generated by Super Admin actions.</p>
      </div>
      <div className="bg-[#0d0d0d] border border-[#1a1a1a] rounded-xl overflow-hidden">
        {loading ? <p className="py-16 text-center text-[#555]">Loading…</p> : tasks.length === 0 ? <p className="py-16 text-center text-[#555]">No tasks found.</p> : (
          <div className="divide-y divide-[#111]">
            {tasks.map(task => (
              <div key={task.id} className="px-5 py-4 flex items-center gap-4">
                <ClipboardList size={18} className="text-[#C5A059] shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-[#DDD]">{task.title}</p>
                  <p className="text-xs text-[#666] mt-1">{task.id} · {task.relatedEntityId} · Assignee {task.assigneeId}</p>
                </div>
                <span className="text-[10px] uppercase text-[#999]">{task.status}</span>
                {task.status !== 'COMPLETED' && (
                  <button onClick={() => completeTask(task.id, token)} className="flex items-center gap-1.5 text-xs text-emerald-400 hover:text-emerald-300">
                    <CheckCircle2 size={14} /> Complete
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
